module.exports = {
    hi: () => console.log('Hi mate!'), // Say hi 👋
    by: () => console.log('Bye!'), // Saying bye 👋
    ok: () => console.log('OK!'), // OK 👍
    thx: () => console.log('Thanks!'), // Thank you 🙏
    lol: () => console.log('LOL!'), // Laughing out loud 😂
    yw: () => console.log('You\'re welcome!'), // You're welcome 😊
    brb: () => console.log('BRB'), // Be right back 🏃
    gn: () => console.log('Good night!'), // Good night 😴
    gm: () => console.log('Good morning!'), // Good morning ☀️
    hf: () => console.log('Have fun!'), // Have fun! 🎉
    ty: () => console.log('Thank you!'), // Thank you 🙏
    pls: () => console.log('Please!'), // Please 🙏
    np: () => console.log('No problem!'), // No problem 👍
    soz: () => console.log('Sorry!'), // Sorry 😔
    omg: () => console.log('OMG!'), // Oh my god 😲
    wut: () => console.log('What?'), // What? 🤔
    yolo: () => console.log('YOLO!'), // You only live once 😎
    aha: () => console.log('Aha!'), // Aha! 💡
    meh: () => console.log('Meh!'), // Meh 😐
    oops: () => console.log('Oops!'), // Oops 😬
    rofl: () => console.log('ROFL!'), // Rolling on floor 😂
    luv: () => console.log('Love!'), // Sending love ❤️
    cya: () => console.log('See ya!'), // See you later 👋
    idk: () => console.log('IDK!'), // I don't know 🤷
    okk: () => console.log('OK!'), // OK 👍
    kk: () => console.log('KK!'), // Okay 👍
    g2g: () => console.log('Got to go!'), // Gotta go now 🏃
    npf: () => console.log('No problem, friend!'), // No problem, friend 👍
    tyvm: () => console.log('Thank you very much!'), // Thank you so much 🙏
    plsplz: () => console.log('Please please!'), // Please please 🙏
    lmao: () => console.log('LMAO!'), // Laughing my ass off 😂
    omgwtf: () => console.log('OMG WTF!'), // OMG WTF 🤯
    smh: () => console.log('SMH!'), // Shaking my head 🤦
    yus: () => console.log('Yes!'), // Yes! 👍
    nah: () => console.log('Nah!'), // No! 🙅
    hmm: () => console.log('Hmm…'), // Hmm 🤔
    woo: () => console.log('Woo!'), // Woo! 🎉
    yay: () => console.log('Yay!'), // Yay! 🎉
    booo: () => console.log('Boo!'), // Boo 👎
    yipee: () => console.log('Yipee!'), // Yipee! 🥳
    bah: () => console.log('Bah!'), // Bah! 😒
    huzzah: () => console.log('Huzzah!'), // Huzzah! 🥳
    cheers: () => console.log('Cheers!'), // Cheers 🥂
    oi: () => console.log('Oi!'), // Oi! 👋
    tallyho: () => console.log('Tally ho!'), // Tally ho! 🐎
    voila: () => console.log('Voila!'), // Voila! ✨
    bingo: () => console.log('Bingo!'), // Bingo! 🎉
    kapow: () => console.log('Kapow!'), // Kapow! 💥
    blimey: () => console.log('Blimey!'), // Blimey! 😲
    crikey: () => console.log('Crikey!') // Crikey! 😲
};